version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm install
      - run:
          name: Run test
          command: npm run test
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    step:
      - checkout
      - run:
        name: "Build Docker Image"
        command: docker build -t pknndev/twitder-ci .
      - run:
        name: "Push to heroku registry container"
        command: |
          echo $HEROKU_API_KEY | docker login -u _ --password-stdin registry.heroku.com
          docker tag pknndev/twitder-ci registry.heroku/twitder-ci-2/web
          docker push registry.heroku/twitder-ci-2/web
      - run:
        name: "Release with heroku"
        command: |
          heroku container:release web -a twitder-ci-2
  workflow:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - deploy:
          requires:
            - build
            - deploy:
              require:
                -build